In [87]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits

In [88]:
digits =load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [89]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=10)

In [90]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [91]:
lr_model = LogisticRegression(max_iter=10000)
lr_model.fit(x_train,y_train)
lr_model.score(x_test,y_test)

0.9527777777777777

In [92]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train, y_train)
dt_model.score(x_test, y_test)

0.8611111111111112

In [93]:
svc_model = SVC()
svc_model.fit(x_train,y_train)
svc_model.score(x_test,y_test)

0.9833333333333333

In [94]:
rf_model = RandomForestClassifier(n_estimators=10)
rf_model.fit(x_train, y_train)
rf_model.score(x_test, y_test)

0.95

In [95]:
def print_accuracy(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return 100*model.score(x_test,y_test)

In [96]:
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=4)

In [97]:
lr_score=[]
dt_score=[]
svc_score=[]
rf_score=[]

In [98]:
for train_index,test_index in skfold.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    
    lr_score.append(print_accuracy(LogisticRegression(max_iter=10000, solver='liblinear'),x_train, x_test, y_train, y_test))
    dt_score.append(print_accuracy(DecisionTreeClassifier(),x_train, x_test, y_train, y_test))
    svc_score.append(print_accuracy(SVC(),x_train, x_test, y_train, y_test))
    rf_score.append(print_accuracy(RandomForestClassifier(n_estimators=10),x_train, x_test, y_train, y_test))

In [99]:
lr_score

[93.77777777777779, 91.0913140311804, 95.7683741648107, 90.42316258351893]

In [100]:
dt_score

[79.55555555555556, 73.2739420935412, 85.96881959910914, 78.39643652561247]

In [101]:
svc_score

[96.22222222222221, 96.65924276169265, 98.21826280623608, 95.10022271714922]

In [102]:
rf_score

[91.33333333333333, 87.52783964365256, 91.98218262806236, 89.086859688196]

In [103]:
from sklearn.model_selection import cross_val_score

In [104]:
cross_val_score(LogisticRegression(max_iter=10000, solver='liblinear'),digits.data, digits.target,cv=4)*100

array([93.77777778, 91.09131403, 95.76837416, 90.42316258])

In [105]:
cross_val_score(DecisionTreeClassifier(),digits.data, digits.target,cv=4)*100

array([80.        , 75.50111359, 83.51893096, 79.06458797])

In [106]:
cross_val_score(SVC(),digits.data, digits.target,cv=4)*100

array([96.22222222, 96.65924276, 98.21826281, 95.10022272])

In [107]:
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target,cv=4)*100

array([92.22222222, 87.08240535, 94.43207127, 89.97772829])

In [108]:
for i in range(1,21):
    s1 = cross_val_score(RandomForestClassifier(n_estimators=5*i),digits.data, digits.target,cv=3)*100
    score = np.average(s1)
    print("n_estimator: {}, accuracy: {}".format(5*i, score))
    

n_estimator: 5, accuracy: 84.52977184195883
n_estimator: 10, accuracy: 90.03895381190874
n_estimator: 15, accuracy: 92.20923761825264
n_estimator: 20, accuracy: 92.2648859209794
n_estimator: 25, accuracy: 92.43183082915971
n_estimator: 30, accuracy: 93.60044518642182
n_estimator: 35, accuracy: 93.37785197551473
n_estimator: 40, accuracy: 93.87868670005564
n_estimator: 45, accuracy: 93.87868670005564
n_estimator: 50, accuracy: 93.26655537006121
n_estimator: 55, accuracy: 93.26655537006121
n_estimator: 60, accuracy: 93.82303839732889
n_estimator: 65, accuracy: 94.04563160823595
n_estimator: 70, accuracy: 93.9343350027824
n_estimator: 75, accuracy: 94.10127991096272
n_estimator: 80, accuracy: 93.1552587646077
n_estimator: 85, accuracy: 93.9343350027824
n_estimator: 90, accuracy: 94.26822481914303
n_estimator: 95, accuracy: 93.82303839732889
n_estimator: 100, accuracy: 94.54646633277684
