In [106]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [107]:
iris=load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [108]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target']=iris.target
df['flower']=df['target'].apply(lambda x: iris.target_names[x])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target     flower  
0         0     setosa  
1         0     setosa  
2         0     setosa  
3         0     setosa  
4         0     setosa  
..      ...        ...  
145       2  virginica  
146       2  virginica  
147       2  virginica  
148       2  virginica  
149       2  virginica  

[150 rows x 6 columns]

In [109]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [110]:
from sklearn.svm import SVC
model=SVC(C=30, kernel='rbf', gamma='auto')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9

Using the K Fold Cross validation

In [111]:
from sklearn.model_selection import cross_val_score

In [112]:
cross_val_score(SVC(C=30, kernel='rbf', gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [113]:
cross_val_score(SVC(C=20, kernel='rbf', gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [114]:
cross_val_score(SVC(C=1, kernel='rbf', gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [115]:
cross_val_score(SVC(C=30, kernel='linear', gamma='auto'),iris.data, iris.target, cv=5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [116]:
cross_val_score(SVC(C=1, kernel='linear', gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [117]:
ker = ['rbf', 'linear']
c = [1,5,10,15,20,25,30]
avg_scores={}

for kval in ker:
    for Cval in c:
        cv_score = cross_val_score(SVC( C=Cval, kernel=kval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_scores[kval+"_"+str(Cval)]=np.average(cv_score)
avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_5': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_15': 0.9733333333333334,
 'rbf_20': 0.9666666666666668,
 'rbf_25': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_5': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_15': 0.9666666666666666,
 'linear_20': 0.9666666666666666,
 'linear_25': 0.96,
 'linear_30': 0.96}

Doing the same as the above for loop easily using GridSearchCV()

In [118]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma='auto'),{
    'C':[1,5,10,15,20,25,30],
    'kernel':['rbf','linear']
    }, cv=5, return_train_score=True)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00244017, 0.00228314, 0.00190005, 0.00212798, 0.0016582 ,
        0.0015748 , 0.00247402, 0.00126987, 0.00164056, 0.00194383,
        0.00133343, 0.00102944, 0.00204892, 0.00235739]),
 'std_fit_time': array([0.00029325, 0.00052052, 0.00073936, 0.00077436, 0.00080825,
        0.00134776, 0.00181571, 0.00026755, 0.00027523, 0.00086294,
        0.00071423, 0.00041738, 0.000543  , 0.00071103]),
 'mean_score_time': array([0.00175195, 0.00113239, 0.00136466, 0.00151534, 0.00092516,
        0.00095725, 0.00131879, 0.00146108, 0.00087085, 0.00126519,
        0.00087457, 0.00041733, 0.00117655, 0.00083065]),
 'std_score_time': array([0.00044858, 0.00032076, 0.00023763, 0.00071872, 0.00020055,
        0.00085785, 0.00053284, 0.00081166, 0.00028852, 0.00069656,
        0.00031263, 0.00020993, 0.00059556, 0.00044757]),
 'param_C': masked_array(data=[1, 1, 5, 5, 10, 10, 15, 15, 20, 20, 25, 25, 30, 30],
              mask=[False, False, False, False, False, False, False, F

In [119]:
df1=pd.DataFrame(clf.cv_results_)
df1

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.002440      0.000293         0.001752        0.000449       1   
1        0.002283      0.000521         0.001132        0.000321       1   
2        0.001900      0.000739         0.001365        0.000238       5   
3        0.002128      0.000774         0.001515        0.000719       5   
4        0.001658      0.000808         0.000925        0.000201      10   
5        0.001575      0.001348         0.000957        0.000858      10   
6        0.002474      0.001816         0.001319        0.000533      15   
7        0.001270      0.000268         0.001461        0.000812      15   
8        0.001641      0.000275         0.000871        0.000289      20   
9        0.001944      0.000863         0.001265        0.000697      20   
10       0.001333      0.000714         0.000875        0.000313      25   
11       0.001029      0.000417         0.000417        0.000210      25   
12       0.002049      0.000543         0.001177        0.000596      30   
13       0.002357      0.000711         0.000831        0.000448      30   

   param_kernel                         params  split0_test_score  \
0           rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1        linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2           rbf      {'C': 5, 'kernel': 'rbf'}           0.966667   
3        linear   {'C': 5, 'kernel': 'linear'}           1.000000   
4           rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
5        linear  {'C': 10, 'kernel': 'linear'}           1.000000   
6           rbf     {'C': 15, 'kernel': 'rbf'}           0.966667   
7        linear  {'C': 15, 'kernel': 'linear'}           1.000000   
8           rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
9        linear  {'C': 20, 'kernel': 'linear'}           1.000000   
10          rbf     {'C': 25, 'kernel': 'rbf'}           0.966667   
11       linear  {'C': 25, 'kernel': 'linear'}           1.000000   
12          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   
13       linear  {'C': 30, 'kernel': 'linear'}           1.000000   

    split1_test_score  split2_test_score  ...  mean_test_score  \
0                 1.0           0.966667  ...         0.980000   
1                 1.0           0.966667  ...         0.980000   
2                 1.0           0.966667  ...         0.980000   
3                 1.0           0.933333  ...         0.980000   
4                 1.0           0.966667  ...         0.980000   
5                 1.0           0.900000  ...         0.973333   
6                 1.0           0.933333  ...         0.973333   
7                 1.0           0.900000  ...         0.966667   
8                 1.0           0.900000  ...         0.966667   
9                 1.0           0.900000  ...         0.966667   
10                1.0           0.900000  ...         0.966667   
11                1.0           0.900000  ...         0.960000   
12                1.0           0.900000  ...         0.960000   
13                1.0           0.900000  ...         0.960000   

    std_test_score  rank_test_score  split0_train_score  split1_train_score  \
0         0.016330                1            0.983333            0.983333   
1         0.016330                1            0.975000            0.975000   
2         0.016330                1            0.975000            0.983333   
3         0.026667                1            0.975000            0.966667   
4         0.016330                1            0.975000            0.966667   
5         0.038873                6            0.966667            0.966667   
6         0.024944                6            0.966667            0.966667   
7         0.042164               10            0.983333            0.966667   
8         0.036515                8            0.966667            0.975000   
9         0.042164               10           

In [120]:
df1[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2        5          rbf         0.980000
3        5       linear         0.980000
4       10          rbf         0.980000
5       10       linear         0.973333
6       15          rbf         0.973333
7       15       linear         0.966667
8       20          rbf         0.966667
9       20       linear         0.966667
10      25          rbf         0.966667
11      25       linear         0.960000
12      30          rbf         0.960000
13      30       linear         0.960000

In [121]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [122]:
clf.best_score_

0.9800000000000001

In [123]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs

Using RandomizedSearchCV()

In [124]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma='auto'), {
        'C': [1,5,10,15,20,25,30],
        'kernel': ['rbf','linear']
    }, 
    cv=5, 
    return_train_score=False, 
    n_iter=3
)
rs.fit(iris.data, iris.target)
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1      10          rbf         0.980000
2      15          rbf         0.973333

Supplying the Models as a parameter in the grid Search, using python Dictionaries

In [125]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [126]:
model_params={
    'svm':{
        'model': SVC(gamma='auto'),
        'params':{
            'C':[1,5,10,15,20,25,30],
            'kernel':['rbf','linear']
        }
    },
    'random_froest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,3,5,7,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,2,4,6,8,10]
        }
    }
}

In [127]:
scores=[]

for model_name, mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'], cv=5)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params':clf.best_params_
    })
df =pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_froest    0.960000        {'n_estimators': 7}
2  logistic_regression    0.966667                   {'C': 4}

So, SVM is the best classification model for this data with hyperparameters, C=1 and kernel='rbf