In [153]:
import numpy as np
import pandas as pd

In [154]:
df = pd.read_csv("salaries.csv")
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [155]:
X=df[['company','job','degree']]
X

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [156]:
Y=df['salary_more_then_100k']
Y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [157]:
from sklearn.preprocessing import LabelEncoder
le_company = LabelEncoder()
le_job = LabelEncoder()
le_degree=LabelEncoder()

In [158]:
X['company_'] = le_company.fit_transform(X.company)
X['job_'] = le_job.fit_transform(X.job)
X['degree_'] = le_degree.fit_transform(X.degree)
X

company                  job     degree  company_  job_  degree_
0       google      sales executive  bachelors         2     2        0
1       google      sales executive    masters         2     2        1
2       google     business manager  bachelors         2     0        0
3       google     business manager    masters         2     0        1
4       google  computer programmer  bachelors         2     1        0
5       google  computer programmer    masters         2     1        1
6   abc pharma      sales executive    masters         0     2        1
7   abc pharma  computer programmer  bachelors         0     1        0
8   abc pharma     business manager  bachelors         0     0        0
9   abc pharma     business manager    masters         0     0        1
10    facebook      sales executive  bachelors         1     2        0
11    facebook      sales executive    masters         1     2        1
12    facebook     business manager  bachelors         1     0        0
13    facebook     business manager    masters         1     0        1
14    facebook  computer programmer  bachelors         1     1        0
15    facebook  computer programmer    masters         1     1        1

In [159]:
X = X.drop(['company','job','degree'], axis='columns')
X

company_  job_  degree_
0          2     2        0
1          2     2        1
2          2     0        0
3          2     0        1
4          2     1        0
5          2     1        1
6          0     2        1
7          0     1        0
8          0     0        0
9          0     0        1
10         1     2        0
11         1     2        1
12         1     0        0
13         1     0        1
14         1     1        0
15         1     1        1

In [160]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X.values, Y.values, test_size=0.2, random_state=10)

In [161]:
x_test

array([[2, 1, 1],
       [2, 0, 1],
       [1, 1, 0],
       [0, 1, 0]])

In [162]:
y_test

array([1, 1, 1, 0], dtype=int64)

In [163]:
from sklearn import tree

model = tree.DecisionTreeClassifier()

In [164]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [165]:
model.predict(x_test)

array([0, 1, 1, 0], dtype=int64)

In [166]:
y_test

array([1, 1, 1, 0], dtype=int64)

In [167]:
model.score(x_test, y_test)

0.75

In [168]:
model.score(X.values, Y.values)

0.9375

In [169]:
#Is salary of Google, Computer Engineer, Bachelors degree > 100 k
if(model.predict([[2,1,0]])==1):
    print("YES")
else:
    print("NO")

NO


In [170]:
#Is salary of Google, Computer Engineer, Masters degree > 100 k ?
if(model.predict([[2,1,1]])==1):
    print("YES")
else:
    print("NO")

NO
